# 最高可擴展的視野距離
# 建議值,伺服器設置4-6,插件設置4-64
# 不影響伺服器本身的視野距離
# 實際上是依照客戶端的視野距離來調整,但如果客戶端條超過此限值,一樣只有此限制的視野距離
# 從此插件延伸的區塊不會載入實體/方塊更新
ExtendViewDistance: 32

# 每個tick可以讀取多少區塊
# 值越低,就需要越多時間玩家才能完成加載所有擴展區塊
# 只讀取已經生成過的區塊,插件不會生成(太耗費性能)
# 切勿過高,伺服器可能會有滯後問題
# 按照 伺服器性能、網路上傳速度、存取I/O性能 做依據,來調整此值
TickSendChunkAmount: 5
# 每個tick能發送給每個玩家多少個封包
# 如果總數已經超過TickSendChunkAmount,則也不會繼續發送
# 切勿比TickSendChunkAmount還高,建議值為TickSendChunkAmount÷5
# 過高的話可能嚴重造成客戶端卡頓,且伺服器可能會短暫排擠某些玩家
PlayerTickSendChunkAmount: 1

# 玩家離區塊太遠,是唪發送區塊卸除請求給玩家(主要適用於客戶端性能)
PlayerOutChunkSendUnload: true

# 多少次tick進行1次區塊權重重新檢查
# 沒有特別要求的話,建議不要調整此值
TickChunkExamine: 40
# 多少次tick進行1次區塊發送
# 沒有特別要求的話,建議不要調整此值
# 過低會造成滯後問題
TickChunkSend: 5